### ISSUE TITLE
Write unit tests for properties

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#119]
# Library name(s)
`UT.Members`

# Subtasks

- [x] Accessors
- [x] Get & Set accessors
- [x] Get & Set existence
- [x] Name
- [x] Raw name
   - [x] Top level declaring type
   - [x] Nested declaring type
- [x] Value type
- [x] Static
- [x] Inheritance modifiers
  - [x] Override
  - [x] Virtual
  - [x] Abstract
  - [x] None

**Comment by hailstorm75** [comment]
1h 36m

**Comment by hailstorm75** [comment]
38m

**Comment by hailstorm75** [comment]
34m

**Comment by hailstorm75** [comment]
9m

**Comment by hailstorm75** [comment]
12m

**Comment by hailstorm75** [comment]
24m

**Comment by hailstorm75** [comment]
24m

**Comment by hailstorm75** [comment]
51m

**Comment by hailstorm75** [comment]
Total: 4h 48m
