### ISSUE TITLE
Refactor IResolver to hide methods

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#122]
# Library name(s)
- `MarkDoc.Members`
- `MarkDoc.Members.Dnlib`

# Description
The `IResolver` type exposes methods which are only used within the the `MarkDoc.Members.*` library. Thus these methods should not be externally visible.

```csharp
IResType Resolve(object source, IReadOnlyDictionary<string, string>? generics = null);

IType? FindReference(object source, IResType type);

IType ResolveType(object subject, object? parent = null);
```

# Subtasks

- [x] Refactor the member type constructors to take the non-interface variant of the resolver
- [x] Remove the existing unit tests that cover mentioned methods
- [x] Remove the methods from the `IResolver` interface
- [x] Modify the accessor from `public` to `internal` in the `Resolver` class from `MarkDoc.Members.Dnlib`

**Comment by hailstorm75** [comment]
Total: 15m
