### ISSUE TITLE
Add support for read-only structs

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#136]
# Library name(s)
- `MarkDoc.Members`
- `MarkDoc.Members.Dnlib`
- `UT.Members`

# Description
```csharp
public readonly struct MyStruct { }
```

# Subtasks

- [x] Enhance the interface
- [x] Implement in the dnlib library
- [x] Enhance the Basic Generator
- [x] Add unit test

**Comment by hailstorm75** [comment]
29m

**Comment by hailstorm75** [comment]
16m

**Comment by hailstorm75** [comment]
33m

**Comment by hailstorm75** [comment]
Total: 1h 18m
