### ISSUE TITLE
Add support for struct read-only properties

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#138]
# Library name(s)
- `MarkDoc.Members`
- `MarkDoc.Members.Dnlib`

# Description
```csharp
public struct MyStruct
{
  private double m_myPropertyGetter;

  public readonly double MyProperty => default;
  public double MyPropertyGetter
  {
      readonly get => m_myPropertyGetter;
      set => m_myPropertyGetter = value;
  }
}
```

# Subtasks

- [x] Enhance the interface
- [x] Implement in the dnlib library
- [x] Enhance the Basic Generator
- [x] Add unit test

**Comment by hailstorm75** [comment]
13m

**Comment by hailstorm75** [comment]
13m
21m

**Comment by hailstorm75** [comment]
Total: 40m
