### ISSUE TITLE
Write unit tests for ResTuple

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#146]
# Library name(s)
`UT.Members`

# Subtasks

- [x] Number of generic paramaters
- [x] Generic parameter types
- [x] IsValueTuple
- [x] Value tuple parameter names
- [x] Tuples within tuples
- [x] Dynamic parameter type support

**Comment by hailstorm75** [comment]
Total: 1h 37m
