### ISSUE TITLE
Add support for records

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Support the new C#9 record type.

**Subtasks**

- [x] Add the record type to the members library
- [x] Make changes if necessary, to the documentation library
- [x] Add generator support
- [x] Create unit tests

**Comment by hailstorm75** [comment]
1h 17min

**Comment by hailstorm75** [comment]
24m

**Comment by hailstorm75** [comment]
6m

**Comment by hailstorm75** [comment]
43m

**Comment by hailstorm75** [comment]
Total: 2h 30m
