### ISSUE TITLE
Add support for property init setters

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#157]
**Is your feature request related to a problem? Please describe.**
Enhance the properties with support for the new C#9 init property setters.

**Subtasks**

- [x] Add support to the members library
- [x] Add support to the documentation library, if needed
- [x] Add support to the generator library
- [x] Cover with unit tests

**Comment by hailstorm75** [comment]
16m

**Comment by hailstorm75** [comment]
1m

**Comment by hailstorm75** [comment]
1h 27m

**Comment by hailstorm75** [comment]
Total: 1h 44m
