### ISSUE TITLE
Improve plugin list view

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#178]
# Library name(s)
 - `MarkDoc.Views.Main`
 - `MarkDoc.ViewModels.Main`

# Description
Modify the plugin view to display a list of available plugins and add the ability to display plugin descriptions, icons, steps, and other metadata.

# Subtasks

- [x] Create UI prototype
- [x] Modify the view
- [x] Modify the view model

**Comment by hailstorm75** [comment]
*Nothing selected*

![Home](https://user-images.githubusercontent.com/16069996/151243954-c4f3118d-c8c3-4cfa-8b3e-72eb32c0624b.png)

*Plugin selected*

![Plugin selected](https://user-images.githubusercontent.com/16069996/151243950-335d359f-be5d-433c-b158-e12ee09b3750.png)
