### ISSUE TITLE
Add summary page logger filtering, sorting, and grouping

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#190]
# Library name(s)
- `MarkDoc.Views.Main`
- `MarkDoc.ViewModels.Main`

# Description
Introduce filtering, sorting, and grouping for the summary page.

Allow the user to:
- group logged entries by their type and source
- filter logged entries by their description
- sort logged entries by their date

# Subtasks

- [x] Prototype the updated summary page design
- [x] Update the summary view
- [x] Implement the logic in the view model
