### ISSUE TITLE
Add ability to toggle Dark mode

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#209]
# Library name(s)
 - `MarkDoc.App`
 - `MarkDoc.Helpers`
 - `MarkDoc.ViewModels.Main`

# Description
Allow the user to toggle between light mode and dark mode in the applications settings menu.

# Subtasks

- [x] Create a theme manager
- [x] Add relevant UI elements into the settings view
- [x] Modify the view model
