### ISSUE TITLE
Implement anchor link creation

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#73]
# Library name(s)
 - `MarkDoc.Linkers`
 - `MarkDoc.Linkers.Markdown`
 - `MarkDoc.Generator.Basic`
 - `MarkDoc.Elements`

# Description
Implement logic for creating heading anchors

# Subtasks

- [x] Add Register anchor method to the `ILinker`
- [x] Refactor the `IElementCreator` to create links lazily
- [x] Modify the generator code to use the new methods
- [x] Create the anchor creating logic

**Comment by hailstorm75** [comment]
17m

**Comment by hailstorm75** [comment]
47m

**Comment by hailstorm75** [comment]
4m

**Comment by hailstorm75** [comment]
2h

**Comment by hailstorm75** [comment]
32m

**Comment by hailstorm75** [comment]
Total: 3h 52m
