### ISSUE TITLE
Create the exporter

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#81]
# Library name(s)
`MarkDoc.Printer`
`MarkDoc.Printer.Markdown`

# Description
Libraries for printing the resulting document(s).

# Subtasks

- [x] Create the interface
- [x] Implement the interface
- [x] Use the new libraries in the console

**Comment by hailstorm75** [comment]
Total: 55m
