### ISSUE TITLE
Reorganize Core interface libraries

### ISSUE THREAD

**Issue by hailstorm75** [hailstorm75/ModularDoc#83]
# Library name(s)
- `MarkDoc.Documentation`
- `MarkDoc.Elements`
- `MarkDoc.Generator`
- `MarkDoc.Linkers`
- `MarkDoc.Members`
- `MarkDoc.Printer`

# Description
Move the interface libraries to a separate folder for interfaces

# Subtasks

- [x] Create the solution folder
- [x] Create the physical folder
- [x] Move the libraries
- [x] Change the build paths

**Comment by hailstorm75** [comment]
Total: 51m
